const express = require('express')
const router = express.Router()
const MenuController = require('../controller/menu.controller')
router.post("/add-menu", MenuController.addMenu)
router.post("/add-menu-image",MenuController.uploadImageAdd.single('image'), MenuController.addMenuWithImage)
router.get("/get-all-menu", MenuController.getAllMenu)
router.put("/update-menu",MenuController.uploadImageUpdate.single('image'), MenuController.updateMenuWithImage)
router.put("/update-menu-image/:id",MenuController.uploadImageAdd.single('menu'), MenuController.updateImage)
router.delete("/delete-menu/:id", MenuController.deleteMenu)
module.exports = router
